name: sauronpub
channels:
  - conda-forge
dependencies:
  - python==3.9.1
  - poetry>=1.1,<2.0
  - tox>=2.22,<3.0
  - pip install git+https://github.com/dmyersturnbull/sauronlab.git/main[perf,extras]
  - pip install git+https://github.com/dmyersturnbull/mandos.git/main
